# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e10cdd608d634435bfc80d84883a71d7b21d2c2d1c7d559f8e659319d27ac0bbaff0a19053462419919d5627e0f7b1051ea556c21a214f0201b70a256a125cb2

test:
  secret_key_base: 173fac34a90f7ad1ada157194067a6066ae23da259211e55678fed7bff0f5bcc230092246aa24efa8f0621f505d71477508067d0a139e11cd5c6a3b5b3221365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
